export const TENANT_PERMISSION = {
  DASHBOARD_VIEW: 'dashboard:view',
  TENANT_VIEW: 'tenant:view',
  TENANT_MANAGE: 'tenant:manage',
  TENANT_USERS_VIEW: 'tenant_users:view',
  TENANT_USERS_MANAGE: 'tenant_users:manage',
  TENANT_USER_KYC_VIEW: 'tenant_user_kyc:view',
  TENANT_USER_KYC_MANAGE: 'tenant_user_kyc:manage',
  TENANT_RBAC_USERS_VIEW: 'tenant_rbac_users:view',
  TENANT_RBAC_USERS_MANAGE: 'tenant_rbac_users:manage',
  TENANT_RBAC_ROLES_VIEW: 'tenant_rbac_roles:view',
  TENANT_RBAC_ROLES_MANAGE: 'tenant_rbac_roles:manage',
  TENANT_RBAC_PERMISSIONS_VIEW: 'tenant_rbac_permissions:view',
  TENANT_RBAC_PERMISSIONS_MANAGE: 'tenant_rbac_permissions:manage',
  WALLETS_VIEW: 'wallets:view',
  HOT_WALLETS_VIEW: 'hot_wallets:view',
  COLD_WALLETS_VIEW: 'cold_wallets:view',
  BALANCE_MONITOR_VIEW: 'balance_monitor:view',
  COLLECTION_VIEW: 'collection:view',
  TRANSACTIONS_VIEW: 'transactions:view',
  TRANSACTIONS_MANAGE: 'transactions:manage',
  INTERNAL_TRANSFERS_VIEW: 'internal_transfers:view',
  DEPOSITS_VIEW: 'deposits:view',
  WITHDRAWALS_VIEW: 'withdrawals:view',
  WITHDRAWAL_RISK_VIEW: 'withdrawal_risk:view',
  WITHDRAWAL_RISK_MANAGE: 'withdrawal_risk:manage',
  SECURITY_2FA: 'security:2fa',
  CARDS_VIEW: 'cards:view',
} as const

export const TENANT_ROLE = {
  SUPER_ADMIN: 'tenant_super_admin',
} as const
